# Generated by Django 3.2.6 on 2021-08-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_doc', models.CharField(max_length=14)),
                ('private', models.BooleanField()),
                ('incomplete', models.BooleanField()),
                ('ticket', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('seller_doc', models.CharField(max_length=14, null=True)),
                ('ticket_average', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('seller_doc_most_frequency', models.CharField(max_length=14, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('invalid_buyer_doc', models.BooleanField()),
                ('invalid_seller_doc', models.BooleanField()),
                ('invalid_seller_doc_most_frequency', models.BooleanField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.file')),
            ],
        ),
    ]
