# Generated by Django 3.2.6 on 2021-08-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='processed',
        ),
    ]
