# Generated by Django 3.2.6 on 2021-08-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_file_processed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('id',)},
        ),
    ]
